{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--b6030d8e-e77e-41fa-9ad1-879ac6387037",
    "created": "2020-05-26T20:29:38.352362Z",
    "modified": "2020-05-26T20:29:38.352362Z",
    "name": "CVE-2017-6301",
    "description": "An issue was discovered in ytnef before 1.9.1. This is related to a patch described as \"\"4 of 9. Out of Bounds Reads."
}