{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--00a0fe1f-c95c-4127-bf01-f8ddadcd93fb",
    "created": "2020-05-26T20:29:48.44466Z",
    "modified": "2020-05-26T20:29:48.44466Z",
    "name": "CVE-2018-16438",
    "description": "An issue was discovered in the HDF HDF5 1.8.20 library. There is an out of bounds read in H5L_extern_query at H5Lexternal.c."
}