{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--8813d2a2-8428-477d-a1c3-03eb27c658a0",
    "created": "2020-05-26T20:29:44.038124Z",
    "modified": "2020-05-26T20:29:44.038124Z",
    "name": "CVE-2018-10855",
    "description": "Ansible 2.5 prior to 2.5.5, and 2.4 prior to 2.4.5, do not honor the no_log task flag for failed tasks. When the no_log flag has been used to protect sensitive data passed to a task from being logged, and that task does not run successfully, Ansible will expose sensitive data in log files and on the terminal of the user running Ansible."
}