{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--f3f86a80-6e86-413f-a849-79d82a6ca1d8",
    "created": "2020-05-26T20:30:04.751778Z",
    "modified": "2020-05-26T20:30:04.751778Z",
    "name": "CVE-2019-20431",
    "description": "In the Lustre file system before 2.12.3, the ptlrpc module has an osd_map_remote_to_local out-of-bounds access and panic due to the lack of validation for specific fields of packets sent by a client. osd_bufs_get in the osd_ldiskfs module does not validate a certain length value."
}