{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--9956d06b-9c5b-4a33-aebe-735414944997",
    "created": "2020-05-26T20:30:02.313204Z",
    "modified": "2020-05-26T20:30:02.313204Z",
    "name": "CVE-2019-16249",
    "description": "OpenCV 4.1.1 has an out-of-bounds read in hal_baseline::v_load in core/hal/intrin_sse.hpp when called from computeSSDMeanNorm in modules/video/src/dis_flow.cpp."
}