{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--92e75789-19b4-47b1-bd4a-bafab7b02074",
    "created": "2020-05-26T20:29:02.906175Z",
    "modified": "2020-05-26T20:29:02.906175Z",
    "name": "CVE-2014-0480",
    "description": "The core.urlresolvers.reverse function in Django before 1.4.14, 1.5.x before 1.5.9, 1.6.x before 1.6.6, and 1.7 before release candidate 3 does not properly validate URLs, which allows remote attackers to conduct phishing attacks via a // (slash slash) in a URL, which triggers a scheme-relative URL to be generated."
}