{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--30bf3cc2-294e-4852-8bfe-87cd990da056",
    "created": "2020-05-26T20:30:01.203248Z",
    "modified": "2020-05-26T20:30:01.203248Z",
    "name": "CVE-2019-14958",
    "description": "JetBrains PyCharm before 2019.2 was allocating a buffer of unknown size for one of the connection processes. In a very specific situation, it could lead to a remote invocation of an OOM error message because of Uncontrolled Memory Allocation."
}