{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--24d78db5-10f7-4b51-a8c2-c2f32d519d65",
    "created": "2020-05-26T20:29:28.772094Z",
    "modified": "2020-05-26T20:29:28.772094Z",
    "name": "CVE-2017-10708",
    "description": "An issue was discovered in Apport through 2.20.x. In apport/report.py, Apport sets the ExecutablePath field and it then uses the path to run package specific hooks without protecting against path traversal. This allows remote attackers to execute arbitrary code via a crafted .crash file."
}