{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--fb42a0a3-1c83-4d5c-acc3-a05b98539992",
    "created": "2020-05-26T20:29:04.339675Z",
    "modified": "2020-05-26T20:29:04.339675Z",
    "name": "CVE-2014-2667",
    "description": "Race condition in the _get_masked_mode function in Lib/os.py in Python 3.2 through 3.5, when exist_ok is set to true and multiple threads are used, might allow local users to bypass intended file permissions by leveraging a separate application vulnerability before the umask has been set to the expected value."
}