{
    "type": "bundle",
    "id": "bundle--7b0421b3-c454-4b8c-a1f8-61094360655e",
    "spec_version": "2.0",
    "objects": [
        {
            "created_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
            "object_marking_refs": [
                "marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"
            ],
            "source_ref": "malware--d9f7383c-95ec-4080-bbce-121c9384457b",
            "target_ref": "attack-pattern--ac08589e-ee59-4935-8667-d845e38fe579",
            "external_references": [
                {
                    "source_name": "McAfee Maze March 2020",
                    "url": "https://www.mcafee.com/blogs/other-blogs/mcafee-labs/ransomware-maze/",
                    "description": "Mundo, A. (2020, March 26). Ransomware Maze. Retrieved May 18, 2020."
                }
            ],
            "description": "[MAZE](https://attack.mitre.org/software/S0449) has disabled dynamic analysis and other security tools including IDA debugger, x32dbg, and OllyDbg.(Citation: McAfee Maze March 2020)",
            "relationship_type": "uses",
            "id": "relationship--dc9d4208-5e09-437e-bdd1-0dbfc4b54355",
            "type": "relationship",
            "modified": "2020-06-24T01:40:07.443Z",
            "created": "2020-05-18T17:31:39.464Z"
        }
    ]
}